import Link from "next/link";
import { prisma } from "@/lib/db";
import { getCurrentUser } from "@/lib/session";

const fallback=[10,8,4] as const;
export default async function Home(){const query=Promise.all([prisma.student.count(),prisma.job.count({where:{status:"open"}}),prisma.employer.count()]);const timeout=new Promise<typeof fallback>(r=>setTimeout(()=>r(fallback),2000));const [[students,jobs,employers],user]=await Promise.all([Promise.race([query,timeout]),getCurrentUser()]);const dashboard=user?.role==="STUDENT"?"/student/dashboard":user?.role==="EMPLOYER"?"/employer/dashboard":user?.role==="UNIVERSITY"?"/university/dashboard":user?.role==="ADMIN"?"/admin/dashboard":"/login";return <main className="home-design">
  <header className="home-nav"><Link href="/" className="home-logo"><span>ϟ</span><b>FURSAH</b></Link><nav><a href="#solutions">Solutions</a><a href="#how-it-works">How it Works</a><a href="#ai-ethics">Responsible AI</a><a href="#metrics">Prototype</a></nav><div>{user?<Link href={dashboard}>Open Dashboard</Link>:<Link href="/login">Sign In</Link>}<Link className="primary" href={user?dashboard:"/login/demo"}>{user?"Continue":"Explore Prototype"}</Link></div></header>
  <section className="home-hero"><div><span className="home-vision">●　ALIGNING WITH SAUDI VISION 2030</span><h1>Bridging Education &amp; <em>Career Readiness</em> with Explainable AI.</h1><p>Fursah connects students, employers, and universities through a transparent, evidence-based matching engine. Empowering the next generation of Saudi talent.</p><div className="home-ctas"><Link href="/login/demo">Explore Prototype</Link><a href="#how-it-works" className="secondary">▷　Watch Demo</a></div></div><div className="home-preview"><header><i/><i/><i/><small>STUDENT CAREER HUB</small><span/></header><div className="home-preview-body"><section className="home-score"><div><small>Career Readiness Score</small><b>84%</b></div><i><em/></i></section><div className="home-preview-grid"><article><small>VERIFIED SKILLS</small><p><span>Python</span><span>Data Analysis</span></p></article><article><small>GAP ANALYSIS</small><p><span>Public Speaking</span></p></article></div><section className="home-opportunity"><small>RECOMMENDED OPPORTUNITY</small><div><i>▦</i><span><b>AI Research Intern</b><small>Aramco • Dhahran</small></span><em><b>96% Match</b><small>Explainable Rec</small></em></div></section></div></div></section>
  <section className="home-principles">{[["⊙","Explainable AI","No black boxes. Every recommendation includes clear reasoning based on evidence-based data points."],["♧","Human Oversight","AI acts as a co-pilot. Decisions are reviewed and validated by university career advisors and hiring managers."],["♢","Privacy-First","Privacy-conscious data handling. Students own their data and control who can see their professional profile."]].map((x,i)=><article key={x[1]}><i className={`p${i}`}>{x[0]}</i><div><h3>{x[1]}</h3><p>{x[2]}</p></div></article>)}</section>
  <section id="solutions" className="home-section home-solutions"><header><h2>A Unified Workforce Ecosystem</h2><p>Fursah creates a feedback loop that benefits all stakeholders in the employment journey.</p></header><div>{[["♙","For Students",["Personalized Skill Maps","Verified Digital Credentials","Transparent Job Matches"]],["▣","For Employers",["Data-Driven Talent Sourcing","Reduced Time-to-Hire","Explainable Candidate Ranking"]],["♧","For Universities",["Curriculum-Market Alignment","Graduate Tracking Insights","Automated Accreditation Reporting"]]].map((x,i)=><article key={String(x[1])}><i className={`s${i}`}>{x[0]}</i><h3>{x[1] as string}</h3><ul>{(x[2] as string[]).map(y=><li key={y}>✓　{y}</li>)}</ul></article>)}</div></section>
  <section id="how-it-works" className="home-section home-workflow"><h2>Seamless Workflow</h2><div>{[["1","Sync & Analyze","Students sync their academic transcripts and projects. Fursah AI analyzes 200+ skill markers."],["2","Identify & Upskill","Receive a Readiness Score and a custom roadmap to bridge gaps identified by real employer demands."],["3","Match & Hire","Smart matching pairs ready candidates with roles and gives employers an explanation report for each fit."]].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
  <section id="ai-ethics" className="home-section home-ethics"><div><h2>Explainable AI: The Foundation of Trust</h2><p>Unlike traditional algorithms, Fursah provides “Reasoning Cards” for every recommendation. AI should be a tool for empowerment, not a black box for exclusion.</p><ul><li>✓　Mitigated bias through audited datasets</li><li>✓　Human-readable decision logs</li><li>✓　Continuous fairness auditing</li></ul></div><article><header><b>AI RECOMMENDATION LOGIC</b><span>Confidence: 94%</span></header><div className="home-candidate"><i>S.A.</i><span><b>Sara Al-Otaibi</b><small>Candidate ID: #88219</small></span></div><section><b>Why this match?</b><p>Candidate demonstrated advanced problem solving through CS401 coursework and achieved 98th percentile in the 2024 Coding Olympiad.</p></section><section className="violet"><b>Skill Alignment</b><p>Full-Stack Engineering <span>High</span></p><i><em/></i></section></article></section>
  <section id="metrics" className="home-metrics">{[[students,"Demo Students"],[jobs,"Sample Opportunities"],[employers,"Demo Employers"],["94%","Rec. Accuracy"]].map((x,i)=><div key={x[1]} className={`m${i}`}><b>{x[0]}</b><span>{x[1]}</span></div>)}</section>
  <section className="home-final"><h2>Ready to transform the future of workforce readiness?</h2><p>Start exploring the Fursah prototype today and see how explainable AI is making a difference.</p><div><Link href="/login/demo">Get Started Now</Link><Link href="/support" className="secondary">Contact Us</Link></div></section>
  </main>}
