import Link from "next/link";
import { prisma } from "@/lib/db";
import SiteHeader from "@/components/SiteHeader";

// Every user-visible string carries a `data-i18n` key so PreferencesControls can
// swap the landing page into Arabic; keys live in the dictionary in that component.
const principles=[["⊙","principle.explainable.title","Explainable AI","principle.explainable.body","No black boxes. Every recommendation includes clear reasoning based on evidence-based data points."],["♧","principle.oversight.title","Human Oversight","principle.oversight.body","AI acts as a co-pilot. Decisions are reviewed and validated by university career advisors and hiring managers."],["♢","principle.privacy.title","Privacy-First","principle.privacy.body","Privacy-conscious data handling. Students own their data and control who can see their professional profile."]] as const;
const solutions=[["♙","solutions.students","For Students",[["solutions.students.1","Personalized Skill Maps"],["solutions.students.2","Verified Digital Credentials"],["solutions.students.3","Transparent Job Matches"]]],["▣","solutions.employers","For Employers",[["solutions.employers.1","Data-Driven Talent Sourcing"],["solutions.employers.2","Reduced Time-to-Hire"],["solutions.employers.3","Explainable Candidate Ranking"]]],["♧","solutions.universities","For Universities",[["solutions.universities.1","Curriculum-Market Alignment"],["solutions.universities.2","Graduate Tracking Insights"],["solutions.universities.3","Automated Accreditation Reporting"]]]] as const;
const workflow=[["1","workflow.sync.title","Sync & Analyze","workflow.sync.body","Students sync their academic transcripts and projects. Fursah AI analyzes 200+ skill markers."],["2","workflow.upskill.title","Identify & Upskill","workflow.upskill.body","Receive a Readiness Score and a custom roadmap to bridge gaps identified by real employer demands."],["3","workflow.match.title","Match & Hire","workflow.match.body","Smart matching pairs ready candidates with roles and gives employers an explanation report for each fit."]] as const;

const fallback=[10,8,4] as const;
export default async function Home(){const query=Promise.all([prisma.student.count(),prisma.job.count({where:{status:"open"}}),prisma.employer.count()]);const timeout=new Promise<typeof fallback>(r=>setTimeout(()=>r(fallback),2000));const [students,jobs,employers]=await Promise.race([query,timeout]);const metrics=[[students,"metrics.students","Demo Students"],[jobs,"metrics.jobs","Sample Opportunities"],[employers,"metrics.employers","Demo Employers"],["94%","metrics.accuracy","Rec. Accuracy"]] as const;return <main className="home-design">
  <SiteHeader onHome />
  <section className="home-hero"><div><Link href="/impact" className="home-vision" data-i18n="hero.vision">●　ALIGNING WITH SAUDI VISION 2030</Link><h1><span data-i18n="hero.title.a">Bridging Education &amp; </span><em data-i18n="hero.title.b">Career Readiness</em><span data-i18n="hero.title.c"> with Explainable AI.</span></h1><p data-i18n="hero.lead">Fursah connects students, employers, and universities through a transparent, evidence-based matching engine. Empowering the next generation of Saudi talent.</p><div className="home-ctas"><Link href="/login/demo" data-i18n="cta.explore">Explore Prototype</Link><a href="#how-it-works" className="secondary" data-i18n="cta.demo">▷　Watch Demo</a></div></div><div className="home-preview"><header><i/><i/><i/><small data-i18n="preview.hub">STUDENT CAREER HUB</small><span/></header><div className="home-preview-body"><section className="home-score"><div><small data-i18n="preview.score">Career Readiness Score</small><b>84%</b></div><i><em/></i></section><div className="home-preview-grid"><article><small data-i18n="preview.verified">VERIFIED SKILLS</small><p><span data-i18n="preview.python">Python</span><span data-i18n="preview.dataAnalysis">Data Analysis</span></p></article><article><small data-i18n="preview.gap">GAP ANALYSIS</small><p><span data-i18n="preview.speaking">Public Speaking</span></p></article></div><section className="home-opportunity"><small data-i18n="preview.recommended">RECOMMENDED OPPORTUNITY</small><div><i>▦</i><span><b data-i18n="preview.role">AI Research Intern</b><small data-i18n="preview.employer">Aramco • Dhahran</small></span><em><b data-i18n="preview.match">96% Match</b><small data-i18n="preview.explainable">Explainable Rec</small></em></div></section></div></div></section>
  <section className="home-principles">{principles.map(([icon,titleKey,title,bodyKey,body],i)=><article key={titleKey}><i className={`p${i}`}>{icon}</i><div><h3 data-i18n={titleKey}>{title}</h3><p data-i18n={bodyKey}>{body}</p></div></article>)}</section>
  <section id="solutions" className="home-section home-solutions"><header><h2 data-i18n="solutions.title">A Unified Workforce Ecosystem</h2><p data-i18n="solutions.lead">Fursah creates a feedback loop that benefits all stakeholders in the employment journey.</p></header><div>{solutions.map(([icon,titleKey,title,items],i)=><article key={titleKey}><i className={`s${i}`}>{icon}</i><h3 data-i18n={titleKey}>{title}</h3><ul>{items.map(([key,label])=><li key={key} data-i18n={key}>✓　{label}</li>)}</ul></article>)}</div></section>
  <section id="how-it-works" className="home-section home-workflow"><h2 data-i18n="workflow.title">Seamless Workflow</h2><div>{workflow.map(([step,titleKey,title,bodyKey,body])=><article key={step}><b>{step}</b><h3 data-i18n={titleKey}>{title}</h3><p data-i18n={bodyKey}>{body}</p></article>)}</div></section>
  <section id="ai-ethics" className="home-section home-ethics"><div><h2 data-i18n="ethics.title">Explainable AI: The Foundation of Trust</h2><p data-i18n="ethics.lead">Unlike traditional algorithms, Fursah provides “Reasoning Cards” for every recommendation. AI should be a tool for empowerment, not a black box for exclusion.</p><ul><li data-i18n="ethics.bias">✓　Mitigated bias through audited datasets</li><li data-i18n="ethics.logs">✓　Human-readable decision logs</li><li data-i18n="ethics.audit">✓　Continuous fairness auditing</li></ul><a className="home-ethics-doc" href="/fursah-ai-readiness-hackathon-submission.pdf" target="_blank" rel="noopener noreferrer" data-i18n="ethics.report">▤　Read the AI Readiness Report (PDF)</a></div><article><header><b data-i18n="ethics.logic">AI RECOMMENDATION LOGIC</b><span data-i18n="ethics.confidence">Confidence: 94%</span></header><div className="home-candidate"><i>S.A.</i><span><b data-i18n="ethics.candidate">Sara Al-Otaibi</b><small data-i18n="ethics.candidateId">Candidate ID: #88219</small></span></div><section><b data-i18n="ethics.why">Why this match?</b><p data-i18n="ethics.reason">Candidate demonstrated advanced problem solving through CS401 coursework and achieved 98th percentile in the 2024 Coding Olympiad.</p></section><section className="violet"><b data-i18n="ethics.alignment">Skill Alignment</b><p><em data-i18n="ethics.skill">Full-Stack Engineering</em> <span data-i18n="ethics.high">High</span></p><i><em/></i></section></article></section>
  <section id="metrics" className="home-metrics">{metrics.map(([value,key,label],i)=><div key={key} className={`m${i}`}><b>{value}</b><span data-i18n={key}>{label}</span></div>)}</section>
  <section className="home-final"><h2 data-i18n="final.title">Ready to transform the future of workforce readiness?</h2><p data-i18n="final.lead">Start exploring the Fursah prototype today and see how explainable AI is making a difference.</p><div><Link href="/login/demo" data-i18n="final.start">Get Started Now</Link><Link href="/support" className="secondary" data-i18n="final.contact">Contact Us</Link></div></section>
  </main>}
