import { redirect } from "next/navigation";
import { prisma } from "@/lib/db";
import { getCurrentStudent } from "@/lib/session";
import { addExperience, addProject } from "@/actions/student";

export default async function EvidencePage() {
  const ctx = await getCurrentStudent(); if (!ctx) redirect("/login");
  const student = await prisma.student.findUniqueOrThrow({ where: { id: ctx.student.id }, include: { projects: true, experiences: true } });
  return <main className="page-shell"><span className="eyebrow">Evidence-based passport</span><h1 className="page-title">Projects and experience evidence</h1><p className="muted">Submit a public portfolio, repository, research, competition, or employer-verification link. An administrator reviews it before the item is marked verified.</p><div className="grid-2" style={{ marginTop: 26, alignItems: "start" }}><section className="card"><h2>Add a project</h2><form action={addProject} className="form-grid"><label>Project title<input className="input" name="title" required/></label><label>Description<textarea className="input" name="description"/></label><label>Evidence URL<input className="input" name="evidenceUrl" type="url" placeholder="https://github.com/..." required/></label><button className="button primary">Submit project for review</button></form><h3 style={{ marginTop: 24 }}>Submitted projects</h3>{student.projects.map(p => <div className="data-row" key={p.id}><div><strong>{p.title}</strong><div className="muted">{p.reviewNote ?? p.evidenceUrl ?? "Self-reported"}</div></div><span className="pill">{p.verificationStatus}</span></div>)}</section><section className="card"><h2>Add experience</h2><form action={addExperience} className="form-grid"><label>Type<select className="input" name="type"><option value="internship">Internship</option><option value="research">Research</option><option value="volunteer">Volunteer</option><option value="competition">Competition</option><option value="hackathon">Hackathon</option><option value="workshop">Workshop</option></select></label><label>Title<input className="input" name="title" required/></label><label>Organization<input className="input" name="org"/></label><label>Months<input className="input" name="months" type="number" min="1" defaultValue="1"/></label><label>Evidence URL<input className="input" name="evidenceUrl" type="url" required/></label><button className="button primary">Submit experience for review</button></form><h3 style={{ marginTop: 24 }}>Submitted experience</h3>{student.experiences.map(e => <div className="data-row" key={e.id}><div><strong>{e.title}</strong><div className="muted">{e.reviewNote ?? e.evidenceUrl ?? "Self-reported"}</div></div><span className="pill">{e.verificationStatus}</span></div>)}</section></div></main>;
}
