import { redirect } from "next/navigation";
import { prisma } from "@/lib/db";
import { getCurrentAdmin } from "@/lib/session";
import { reviewPortfolioEvidence } from "@/actions/governance";
import { reviewEvidenceDocument } from "@/actions/documents";
import EmptyState from "@/components/EmptyState";

export default async function EvidencePage() {
  const ctx = await getCurrentAdmin(); if (!ctx) redirect("/login");
  const [projects, experiences, documents] = await Promise.all([prisma.project.findMany({ where: { verificationStatus: "PENDING" }, include: { student: { include: { user: true } } } }), prisma.experience.findMany({ where: { verificationStatus: "PENDING" }, include: { student: { include: { user: true } } } }),prisma.evidenceDocument.findMany({where:{reviewStatus:"PENDING"},include:{owner:true},orderBy:{createdAt:"asc"}}).catch(error=>{console.error("Unable to load private evidence documents",error);return [];})]);
  const items = [...projects.map(x => ({ ...x, entityType: "PROJECT" })), ...experiences.map(x => ({ ...x, entityType: "EXPERIENCE" }))];
  return <main className="page-shell"><span className="eyebrow">Evidence integrity</span><h1 className="page-title">Document and link verification</h1><p className="muted">Automated checks organize and flag evidence. A human administrator must inspect every document before it can become verified.</p><section className="card" style={{ marginTop: 26 }}><h2>Private document review</h2>{documents.length?documents.map(document=><form action={reviewEvidenceDocument} className="data-row document-review-row" key={document.id}><input type="hidden" name="documentId" value={document.id}/><div><span className={`pill status-${document.aiStatus==="FLAGGED"?"rejected":"pending"}`}>AI {document.aiStatus.toLowerCase()}</span><strong>{document.originalName}</strong><span className="muted">{document.owner.name} · {document.contextType.replaceAll("_"," ")} · {(document.sizeBytes/1024).toFixed(1)} KB</span><span className="muted">{document.aiNote}</span><a className="link" href={`/api/documents/${document.id}`}>Download private document</a></div><label>Human review note<textarea className="input" name="reviewNote" required placeholder="Record what you inspected and why it is acceptable, or explain what must be replaced."/></label><div className="actions"><button className="button primary" name="decision" value="APPROVED">Approve</button><button className="button danger" name="decision" value="REJECTED">Reject</button></div></form>):<EmptyState tone="clear" icon="✓" title="No documents awaiting review" body="When a student attaches a certificate, CV or project file, the automated check runs first and the document then waits here for your decision." />}</section><section className="card" style={{ marginTop: 18 }}><h2>Submitted evidence links</h2>{items.length ? items.map(item => <form action={reviewPortfolioEvidence} className="data-row" key={`${item.entityType}-${item.id}`}><input type="hidden" name="entityType" value={item.entityType}/><input type="hidden" name="entityId" value={item.id}/><div style={{ flex: 1 }}><span className="pill">{item.entityType}</span><strong style={{ display: "block", marginTop: 8 }}>{item.title}</strong><div className="muted">{item.student.user.name}</div>{item.evidenceUrl && <a className="link" href={item.evidenceUrl} target="_blank" rel="noreferrer">Open submitted evidence</a>}<textarea className="input" name="note" placeholder="Review note; required when rejecting"/></div><button className="button primary" name="decision" value="APPROVED">Approve</button><button className="button danger" name="decision" value="REJECTED">Reject</button></form>) : <EmptyState tone="clear" icon="✓" title="No links awaiting review" body="Public evidence links submitted with projects and experience are checked separately, because their contents can change after submission." />}</section></main>;
}
