import { redirect } from "next/navigation";
import { prisma } from "@/lib/db";
import { getCurrentStudent } from "@/lib/session";
import { addExperience, addProject } from "@/actions/student";
import DocumentUpload from "@/components/DocumentUpload";
import SubmitStatusForm from "@/components/SubmitStatusForm";

export default async function EvidencePage() {
  const ctx = await getCurrentStudent(); if (!ctx) redirect("/login");
  const student = await prisma.student.findUniqueOrThrow({ where: { id: ctx.student.id }, include: { projects: true, experiences: true } });
  return <main className="page-shell"><span className="eyebrow">Evidence-based passport</span><h1 className="page-title">Projects and experience evidence</h1><p className="muted">Upload private supporting documents or add a public evidence link. Automated checks screen the submission first; an administrator makes the final verification decision.</p><div className="grid-2" style={{ marginTop: 26, alignItems: "start" }}><section className="card"><h2>Add a project</h2><SubmitStatusForm action={addProject} submitLabel="Submit project for review" pendingLabel="Submitting project…" successMessage="Project submitted. Automated checks have started and an administrator will make the final verification decision."><label>Project title<input className="input" name="title" required/></label><label>Description<textarea className="input" name="description"/></label><label>Evidence URL (optional)<input className="input" name="evidenceUrl" type="url" placeholder="https://github.com/..."/></label><DocumentUpload label="Project evidence"/></SubmitStatusForm><h3 style={{ marginTop: 24 }}>Submitted projects</h3>{student.projects.map(p => <div className="data-row" key={p.id}><div><strong>{p.title}</strong><div className="muted">{p.reviewNote ?? p.evidenceUrl ?? "Evidence submitted privately"}</div></div><span className="pill">{p.verificationStatus}</span></div>)}</section><section className="card"><h2>Add experience</h2><SubmitStatusForm action={addExperience} submitLabel="Submit experience for review" pendingLabel="Submitting experience…" successMessage="Experience submitted. Automated checks have started and an administrator will make the final verification decision."><label>Type<select className="input" name="type"><option value="internship">Internship</option><option value="research">Research</option><option value="volunteer">Volunteer</option><option value="competition">Competition</option><option value="hackathon">Hackathon</option><option value="workshop">Workshop</option></select></label><label>Title<input className="input" name="title" required/></label><label>Organization<input className="input" name="org"/></label><label>Months<input className="input" name="months" type="number" min="1" defaultValue="1"/></label><label>Evidence URL (optional)<input className="input" name="evidenceUrl" type="url"/></label><DocumentUpload label="Experience evidence"/></SubmitStatusForm><h3 style={{ marginTop: 24 }}>Submitted experience</h3>{student.experiences.map(e => <div className="data-row" key={e.id}><div><strong>{e.title}</strong><div className="muted">{e.reviewNote ?? e.evidenceUrl ?? "Evidence submitted privately"}</div></div><span className="pill">{e.verificationStatus}</span></div>)}</section></div></main>;
}
