/* Saudi employers shown in the student company directory. Listing a company here
   only makes it explorable and followable — it is not a partnership claim and
   does not imply an open vacancy (see the disclaimer on the interests page).
   Sorted case-insensitively so the A-Z browse strip matches the render order. */
export const SAUDI_COMPANY_DIRECTORY = [
  { company: "Abdul Latif Jameel", industry: "Automotive and Investment" },
  { company: "Abdullah Al Othaim Markets", industry: "Retail" },
  { company: "ACWA Power", industry: "Energy and Utilities" },
  { company: "Advanced Petrochemical Company", industry: "Petrochemicals" },
  { company: "Al Bawani", industry: "Construction" },
  { company: "Al Hammadi Holding", industry: "Healthcare" },
  { company: "Al Rajhi Bank", industry: "Banking" },
  { company: "Alamar Foods", industry: "Food and Beverage" },
  { company: "alfanar", industry: "Electrical Manufacturing" },
  { company: "Alinma Bank", industry: "Banking" },
  { company: "Alkhorayef Group", industry: "Industrial Services" },
  { company: "Almajdouie Group", industry: "Logistics" },
  { company: "Almarai", industry: "Food and Beverage" },
  { company: "Arab National Bank", industry: "Banking" },
  { company: "Bahri", industry: "Maritime Logistics" },
  { company: "Bank Albilad", industry: "Banking" },
  { company: "Bank AlJazira", industry: "Banking" },
  { company: "Banque Saudi Fransi", industry: "Banking" },
  { company: "BinDawood Holding", industry: "Retail" },
  { company: "Bupa Arabia", industry: "Insurance and Healthcare" },
  { company: "Ceer", industry: "Automotive" },
  { company: "Cenomi", industry: "Real Estate and Retail" },
  { company: "Dar Al Arkan", industry: "Real Estate Development" },
  { company: "Diriyah Company", industry: "Tourism and Development" },
  { company: "Dr. Sulaiman Al Habib Medical Group", industry: "Healthcare" },
  { company: "Elm", industry: "Digital Solutions" },
  { company: "Emaar The Economic City", industry: "Real Estate Development" },
  { company: "Fakeeh Care Group", industry: "Healthcare" },
  { company: "flynas", industry: "Aviation" },
  { company: "Foodics", industry: "Technology" },
  { company: "Geidea", industry: "Financial Technology" },
  { company: "HungerStation", industry: "Technology and Delivery" },
  { company: "Jabal Omar Development Company", industry: "Real Estate Development" },
  { company: "Jahez International", industry: "Technology and Delivery" },
  { company: "Jarir Marketing Company", industry: "Retail" },
  { company: "Lean Business Services", industry: "Healthcare Technology" },
  { company: "Ma'aden", industry: "Mining" },
  { company: "MBC Group", industry: "Media" },
  { company: "Mobily", industry: "Telecommunications" },
  { company: "Mouwasat Medical Services", industry: "Healthcare" },
  { company: "Nahdi Medical Company", industry: "Healthcare and Retail" },
  { company: "Nana", industry: "Technology and E-commerce" },
  { company: "NEOM", industry: "Development and Technology" },
  { company: "Nesma & Partners", industry: "Construction" },
  { company: "NUPCO", industry: "Healthcare Procurement" },
  { company: "Panda Retail Company", industry: "Retail" },
  { company: "Petro Rabigh", industry: "Petrochemicals" },
  { company: "Petromin Corporation", industry: "Automotive Services" },
  { company: "Public Investment Fund", industry: "Investment" },
  { company: "Qiddiya Investment Company", industry: "Entertainment and Development" },
  { company: "Rasan", industry: "Financial Technology" },
  { company: "Red Sea Global", industry: "Tourism and Development" },
  { company: "Riyad Bank", industry: "Banking" },
  { company: "Riyadh Air", industry: "Aviation" },
  { company: "ROSHN Group", industry: "Real Estate Development" },
  { company: "SABB", industry: "Banking" },
  { company: "SABIC", industry: "Chemicals and Manufacturing" },
  { company: "SAL Saudi Logistics Services", industry: "Logistics" },
  { company: "Salla", industry: "Technology and E-commerce" },
  { company: "Saudi Arabia Railways", industry: "Transport" },
  { company: "Saudi Aramco", industry: "Energy" },
  { company: "Saudi Automotive Services Company", industry: "Automotive Services" },
  { company: "Saudi Cement Company", industry: "Construction Materials" },
  { company: "Saudi Ceramics", industry: "Manufacturing" },
  { company: "Saudi Electricity Company", industry: "Energy and Utilities" },
  { company: "Saudi German Health", industry: "Healthcare" },
  { company: "Saudi Ground Services", industry: "Aviation Services" },
  { company: "Saudi National Bank", industry: "Banking" },
  { company: "Saudi Post | SPL", industry: "Logistics" },
  { company: "Saudia", industry: "Aviation" },
  { company: "Savvy Games Group", industry: "Gaming and Entertainment" },
  { company: "Seera Group", industry: "Travel and Tourism" },
  { company: "Sipchem", industry: "Petrochemicals" },
  { company: "solutions by stc", industry: "Digital Solutions" },
  { company: "SRMG", industry: "Media" },
  { company: "stc", industry: "Telecommunications" },
  { company: "Tabby", industry: "Financial Technology" },
  { company: "Tahakom", industry: "Security Technology" },
  { company: "Tamara", industry: "Financial Technology" },
  { company: "Tawuniya", industry: "Insurance" },
  { company: "The Saudi Investment Bank", industry: "Banking" },
  { company: "Thiqah Business Services", industry: "Digital Solutions" },
  { company: "Unifonic", industry: "Technology" },
  { company: "United Electronics Company", industry: "Retail" },
  { company: "Yanbu National Petrochemical Company", industry: "Petrochemicals" },
  { company: "Zain KSA", industry: "Telecommunications" },
  { company: "Zamil Industrial", industry: "Industrial Manufacturing" },
] as const;

export function companyDirectoryEmail(company: string) {
  const slug = company.toLowerCase().replace(/[^a-z0-9]+/g, ".").replace(/^\.|\.$/g, "");
  return `directory+${slug}@fursah.demo`;
}
