export const SAUDI_COMPANY_DIRECTORY = [
  { company: "ACWA Power", industry: "Energy and Utilities" },
  { company: "Al Rajhi Bank", industry: "Banking" },
  { company: "Alamar Foods", industry: "Food and Beverage" },
  { company: "Almarai", industry: "Food and Beverage" },
  { company: "Arab National Bank", industry: "Banking" },
  { company: "Bank Albilad", industry: "Banking" },
  { company: "Bank AlJazira", industry: "Banking" },
  { company: "Banque Saudi Fransi", industry: "Banking" },
  { company: "Bupa Arabia", industry: "Insurance and Healthcare" },
  { company: "Ceer", industry: "Automotive" },
  { company: "Diriyah Company", industry: "Tourism and Development" },
  { company: "Dr. Sulaiman Al Habib Medical Group", industry: "Healthcare" },
  { company: "Elm", industry: "Digital Solutions" },
  { company: "flynas", industry: "Aviation" },
  { company: "Foodics", industry: "Technology" },
  { company: "HungerStation", industry: "Technology and Delivery" },
  { company: "Jarir Marketing Company", industry: "Retail" },
  { company: "Ma'aden", industry: "Mining" },
  { company: "Mobily", industry: "Telecommunications" },
  { company: "Nahdi Medical Company", industry: "Healthcare and Retail" },
  { company: "NEOM", industry: "Development and Technology" },
  { company: "Qiddiya Investment Company", industry: "Entertainment and Development" },
  { company: "Red Sea Global", industry: "Tourism and Development" },
  { company: "Riyad Bank", industry: "Banking" },
  { company: "ROSHN Group", industry: "Real Estate Development" },
  { company: "SABB", industry: "Banking" },
  { company: "SABIC", industry: "Chemicals and Manufacturing" },
  { company: "Salla", industry: "Technology and E-commerce" },
  { company: "Saudi Aramco", industry: "Energy" },
  { company: "Saudi Electricity Company", industry: "Energy and Utilities" },
  { company: "Saudi German Health", industry: "Healthcare" },
  { company: "Saudi National Bank", industry: "Banking" },
  { company: "Saudia", industry: "Aviation" },
  { company: "Savvy Games Group", industry: "Gaming and Entertainment" },
  { company: "solutions by stc", industry: "Digital Solutions" },
  { company: "stc", industry: "Telecommunications" },
  { company: "Tamara", industry: "Financial Technology" },
  { company: "Tawuniya", industry: "Insurance" },
  { company: "Zain KSA", industry: "Telecommunications" },
] as const;

export function companyDirectoryEmail(company: string) {
  const slug = company.toLowerCase().replace(/[^a-z0-9]+/g, ".").replace(/^\.|\.$/g, "");
  return `directory+${slug}@fursah.demo`;
}
