import {redirect} from "next/navigation";
import {getCurrentEmployer} from "@/lib/session";
import {getAllCareerTracksAsync} from "@/lib/careerTracks.server";
import {createJob} from "@/actions/employer";
import Link from "next/link";
import {JobDraftActions,JobPublishButton,JobSaveStatus} from "@/components/JobDraftControls";
import EmployerHeader from "@/components/EmployerHeader";
import JobHiringAssistant from "@/components/JobHiringAssistant";
import {prisma} from "@/lib/db";
import {getTalentAvailability} from "@/lib/intelligence";
import DocumentUpload from "@/components/DocumentUpload";

function Section({title,number,icon,children}:{title:string;number:string;icon:string;children:React.ReactNode}){return <section className="pjob-section"><header><h2>{icon}　{title}</h2><small>SECTION {number}/04</small></header><div className="pjob-section-body">{children}</div></section>}
export default async function NewJob(){const ctx=await getCurrentEmployer();if(!ctx)redirect("/login");if(ctx.employer.verificationStatus!=="APPROVED")return <main className="pjob-pending"><h1>Create Job Opportunity</h1><p>Your employer account is pending administrator verification. Once approved, you&apos;ll be able to publish roles here.</p></main>;const [tracks,recentJobs]=await Promise.all([getAllCareerTracksAsync(),prisma.job.findMany({where:{employerId:ctx.employer.id},orderBy:{createdAt:"desc"},take:2})]);const availability=await getTalentAvailability({careerTrackId:tracks[0]?.id??null});return <main className="pjob-page">
  <EmployerHeader company={ctx.employer.company} userName={ctx.user.name} active="post"/>
  <header className="pjob-top"><div><small><Link href="/employer/dashboard">OPPORTUNITIES</Link>　›　CREATE NEW OPPORTUNITY</small><h1>Create Job Opportunity</h1></div><Link className="pjob-discard" href="/employer/dashboard">Discard</Link><JobSaveStatus/></header>
  <form id="create-job-form" action={createJob}><div className="pjob-layout"><div className="pjob-main">
    <Section title="Basic Information" number="01" icon="ⓘ"><label className="wide">Job Title<input name="title" placeholder="e.g. Senior Software Engineer, Platform" required/><small>A clear, standard title helps the AI match candidates more accurately.</small></label><label>Department<select name="department"><option>Engineering</option><option>Product</option><option>Data & AI</option></select></label><label>Career Track<select name="careerTrack">{tracks.map(t=><option value={t.id} key={t.id}>{t.label}</option>)}</select></label><label>Employment Type<select name="employmentType"><option>Full-time</option><option>Part-time</option><option>Contract</option></select></label><label>Location<input name="location" placeholder="e.g. Riyadh, Saudi Arabia"/></label><fieldset className="wide"><legend>Work Arrangement</legend><div className="pjob-arrangement"><label><input type="radio" name="arrangement" value="on-site" defaultChecked/>⌂　 On-site</label><label><input type="radio" name="arrangement" value="hybrid"/>♙　 Hybrid</label><label><input type="radio" name="arrangement" value="remote"/>◎　 Remote</label></div></fieldset></Section>
    <Section title="Role Description" number="02" icon="☰"><div className="pjob-editor wide"><header>B　　<i>I</i>　　☷　　☷　　│　　↗</header><textarea name="description" placeholder="Describe responsibilities, expected outcomes, and what success looks like..."/><aside><b>✦　WRITING TIP</b><p>Use action-oriented language. Instead of “Responsible for reports,” try “Delivers weekly performance insights to key stakeholders to drive quarterly strategy.”</p></aside></div><div className="wide"><DocumentUpload label="Job description or requirements document"/></div></Section>
    <Section title="Candidate Requirements" number="03" icon="▣">{/*
      * These fields start empty on purpose. They used to be pre-filled with
      * "React.js:3, Node.js:3, PostgreSQL:3" and matching decorative chips, so
      * a role published without editing them silently required three skills
      * nobody had asked for - which then drove candidate ranking, skill demand,
      * and every university's curriculum gap.
      */}<label>Required Skills<input name="skills" placeholder="e.g. Python:3, SQL:2"/><small>Name:weight, comma separated. Weight 1 to 3, where 3 is essential to the role.</small></label><label>Preferred Skills (Nice-to-have)<input name="preferredSkills" placeholder="e.g. Terraform:1"/><small>Scored, but weighted far below the required skills above.</small></label><label>Minimum Experience<select name="minExperience" defaultValue="0"><option value="0">No minimum</option><option value="6">6 months</option><option value="12">1 year</option><option value="36">3-5 years</option><option value="60">5+ years</option></select></label><label>Education Level<select name="educationLevel" defaultValue=""><option value="">Not specified</option><option>High School</option><option>Diploma</option><option>Bachelor&apos;s Degree</option><option>Master&apos;s Degree</option><option>Doctorate</option></select><small>Shown on the role. Not used to rank candidates.</small></label><label>Languages<input name="languages" placeholder="e.g. Arabic, English"/><small>Shown on the role. Not used to rank candidates.</small></label><label className="wide certs">Required Certifications<input name="certifications" placeholder="Comma separated, e.g. AWS Certified Cloud Practitioner"/></label></Section>
    <Section title="Hiring Preferences" number="04" icon="⚙">{/*
      * Only the setting the platform actually implements is offered. Three
      * further switches used to sit here - portfolio required, recent
      * graduates accepted, AI-assisted ranking - with no name attribute, no
      * column and no reader: toggling them changed nothing, while presenting
      * themselves as saved hiring policy. Evidence-based ranking is not
      * optional on Fursah, so a switch for it would have been misleading even
      * if it had been wired.
      */}<div className="pjob-switch-grid wide"><label><input type="checkbox" name="blindReview" defaultChecked/><i/><span><b>Blind candidate review</b><small>Hide names, gender, and photos to reduce unconscious bias in the early stages.</small></span></label><label><input type="checkbox" name="portfolioRequired"/><i/><span><b>Portfolio required</b><small>Candidates must attach a CV, portfolio or work sample to apply. They are told before they apply and cannot submit without one.</small></span></label><label><input type="checkbox" name="recentGraduatesAccepted" defaultChecked/><i/><span><b>Recent graduates accepted</b><small>Shown on the role so early-career candidates know they are welcome to apply. It does not affect how anyone is ranked.</small></span></label></div><p className="pjob-note">Candidate ranking always uses the structured skill, certification and experience evidence above, and never a personal characteristic. Career stage is not an input, which is why &ldquo;recent graduates accepted&rdquo; is a statement to candidates rather than a filter. Ranking is decision support: you make the hiring decision.</p></Section>
    <section className="pjob-oversight"><span>▣</span><div><b>Responsible AI Oversight</b><p>AI helps evaluate and organize candidate evidence. Final hiring decisions always remain under human oversight.</p></div><Link href="/policies/responsible-ai">Learn More</Link></section>
  </div><aside className="pjob-aside"><JobHiringAssistant studentPoolSize={availability.studentPoolSize} studentsTargetingTrack={availability.studentsTargetingTrack} careerTrackLabel={availability.careerTrackLabel}/><section className="pjob-recent"><h3>RELATED RECENT POSTINGS</h3>{recentJobs.length?recentJobs.map(job=><Link href={`/employer/jobs/${job.id}`} key={job.id}><b>{job.title}</b><span>{job.careerTrack.replaceAll("-"," ")} • {job.createdAt.toLocaleDateString("en-SA",{month:"short",day:"numeric"})}</span><i>→</i></Link>):<p>No previous opportunities yet.</p>}</section></aside></div>
  <footer className="pjob-footer"><JobDraftActions/><span><small>CURRENT TALENT POOL</small><b>{availability.studentPoolSize} student profile(s){availability.careerTrackLabel?` · ${availability.studentsTargetingTrack} targeting ${availability.careerTrackLabel}`:""}</b></span><JobPublishButton/></footer></form>
  </main>}
