import { notFound } from "next/navigation";

const POLICIES = {
  privacy: { title: "Privacy Policy", updated: "4 August 2026", intro: "Fursah collects only the information needed to provide career-readiness, opportunity-matching, verification, and institutional-insight services.", sections: [["Information we use", "Account details, student-provided profile data, verified evidence, opportunity requirements, application activity, and consented outcome feedback."], ["How information is used", "To calculate explainable readiness and match results, recommend development actions, verify evidence, support applications, and produce de-identified institutional insights."], ["Your controls", "Students can manage purpose-specific consent and request access, correction, review, or deletion. Identifiable information is not included in university aggregate reports."], ["Retention and security", "Information should be retained only for a documented purpose, protected through role-based access, and removed or de-identified when it is no longer required."]] },
  terms: { title: "Terms of Use", updated: "4 August 2026", intro: "Fursah is a decision-support platform. Its scores and recommendations do not guarantee admission, certification, employment, or job performance.", sections: [["Responsible use", "Users must provide accurate information, respect others' privacy, and avoid manipulating evidence, rankings, or feedback."], ["Human decisions", "Employers, universities, reviewers, and students remain responsible for consequential decisions. Automated results must not be used as the sole basis for rejection."], ["Availability", "Prototype services may change, contain incomplete data, or be temporarily unavailable while the system is evaluated."], ["Account action", "Access may be restricted when an account is used fraudulently, unlawfully, or in a way that harms other users."]] },
  "responsible-ai": { title: "Responsible AI Policy", updated: "4 August 2026", intro: "Fursah uses transparent, reviewable automation designed to support—not replace—human judgment.", sections: [["Explainability", "Readiness and job-match results show the inputs, gaps, weights, and model or ruleset version used."], ["Fairness", "Protected characteristics are excluded from ranking inputs. Outcomes should be monitored for uneven impact, data imbalance, and inappropriate proxies."], ["Human oversight", "High-impact employment and education decisions require a named human decision-maker, recorded justification, and an appeal route."], ["Monitoring", "Models and rules should be tested in a sandbox, monitored for drift and quality, and rolled back when safeguards fail."]] },
  accessibility: { title: "Accessibility Statement", updated: "4 August 2026", intro: "Fursah aims to provide an inclusive experience for users with different abilities, devices, languages, and connection speeds.", sections: [["Our approach", "We aim for keyboard access, clear focus states, readable contrast, descriptive labels, responsive layouts, and understandable language."], ["Compatibility", "The service is designed for current standards-based browsers and responsive use on mobile and desktop devices."], ["Feedback", "If a feature or document is difficult to access, contact support and include the page, device, and assistance needed."], ["Continuous improvement", "Accessibility issues are treated as product defects and prioritized according to their effect on task completion."]] },
} as const;

export default async function PolicyPage({ params }: { params: Promise<{ policy: string }> }) {
  const { policy } = await params;
  const content = POLICIES[policy as keyof typeof POLICIES];
  if (!content) notFound();
  return <main className="page-shell" style={{ maxWidth: 820 }}><span className="eyebrow">Fursah policies</span><h1 className="page-title">{content.title}</h1><p className="muted">Last updated: {content.updated}</p><div className="notice" style={{ marginTop: 24 }}>{content.intro}</div>{content.sections.map(([title, body]) => <section className="card" style={{ marginTop: 18 }} key={title}><h2>{title}</h2><p className="muted">{body}</p></section>)}<p className="muted" style={{ marginTop: 24 }}>This prototype policy will be expanded and reviewed alongside the project&apos;s policy knowledge base before production use.</p></main>;
}
