import { redirect } from "next/navigation";
import { prisma } from "@/lib/db";
import { getCurrentAdmin } from "@/lib/session";
import { createGovernanceScenario, decideGovernanceScenario, resolveAppeal } from "@/actions/governance";

const PIPELINE = [
  ["Source", "Profiles, jobs, offerings and outcomes", "ACTIVE"], ["Collector", "Validated role-based inputs", "ACTIVE"], ["Preprocessor", "Normalization and data minimization", "ACTIVE"], ["Model", "Readiness, matching and recommendation rules", "ACTIVE"], ["Policy", "Consent, review thresholds and safeguards", "ACTIVE"], ["Distributor", "Role-authorized recommendations", "ACTIVE"], ["Inference target", "Student, employer and university workflows", "ACTIVE"], ["Sandbox", "Scenario evaluation before activation", "PROTOTYPE"], ["Orchestrator", "Version, approval, audit and rollback controls", "PROTOTYPE"], ["Sink", "Dashboards, notifications and exports", "ACTIVE"],
];

export default async function GovernancePage() {
  const ctx = await getCurrentAdmin(); if (!ctx) redirect("/login");
  const [scenarios, appeals, audits] = await Promise.all([prisma.governanceScenario.findMany({ orderBy: { createdAt: "desc" } }), prisma.appeal.findMany({ include: { student: { include: { user: true } } }, orderBy: { createdAt: "desc" } }), prisma.auditEvent.findMany({ orderBy: { createdAt: "desc" }, take: 20 })]);
  return <main className="page-shell"><span className="eyebrow">Responsible AI operations</span><h1 className="page-title">Governance and human oversight</h1><p className="muted">Test high-impact situations, review automated recommendations and trace the ITU-T Y.3172-style pipeline.</p>
    <div className="grid-2" style={{ marginTop: 26, alignItems: "start" }}><section className="card"><h2>Scenario simulator</h2><form action={createGovernanceScenario} className="form-grid"><label>Scenario title<input className="input" name="title" required/></label><label>Risk category<select className="input" name="scenarioType"><option value="AUTOMATED_HIRING">Automated hiring decision</option><option value="DATA_SHARING">Data sharing</option><option value="MODEL_DRIFT">Bias or model drift</option><option value="OTHER">Other</option></select></label><label>Description<textarea className="input" name="description" placeholder="Example: Automatically reject every candidate below a 70% match." required/></label><button className="button primary">Run sandbox checks</button></form></section><section className="card"><h2>Human review queue</h2>{appeals.length ? appeals.map(a => <form action={resolveAppeal} className="data-row" key={a.id}><input type="hidden" name="appealId" value={a.id}/><div style={{ flex: 1 }}><strong>{a.student.user.name} · {a.subjectType}</strong><div className="muted">{a.reason}</div><textarea className="input" name="resolution" placeholder="Resolution and corrective action" required/></div><select className="input" name="status"><option value="RESOLVED">Resolve</option><option value="REJECTED">Reject</option><option value="UNDER_REVIEW">Keep reviewing</option></select><button className="button secondary">Record</button></form>) : <div className="notice">No review requests.</div>}</section></div>
    <section className="card" style={{ marginTop: 18 }}><h2>Scenario results</h2>{scenarios.map(s => { const issues = JSON.parse(s.detectedIssues) as string[]; return <form action={decideGovernanceScenario} className="data-row" key={s.id} style={{ alignItems: "end" }}><input type="hidden" name="scenarioId" value={s.id}/><div style={{ flex: 1 }}><div><span className={`pill status-${s.riskLevel === "HIGH" ? "rejected" : "pending"}`}>{s.riskLevel} RISK</span> <span className="pill">{s.humanDecision}</span></div><strong style={{ display: "block", marginTop: 8 }}>{s.title}</strong><div className="muted">{issues.join(" · ")}</div><div className="notice" style={{ marginTop: 8 }}>{s.proposedAction}</div></div><textarea className="input" name="note" placeholder="Required human justification" required/><button className="button secondary" name="decision" value="APPROVED">Approve control</button><button className="button danger" name="decision" value="OVERRIDDEN">Override</button></form>; })}</section>
    <section className="card" style={{ marginTop: 18 }}><span className="eyebrow">ITU-T Y.3172 traceability</span><h2>Operational pipeline map</h2><div className="grid-2">{PIPELINE.map(([name, implementation, status]) => <div className="data-row" key={name}><div><strong>{name}</strong><div className="muted">{implementation}</div></div><span className="pill">{status}</span></div>)}</div></section>
    <section className="card" style={{ marginTop: 18 }}><h2>Decision audit trail</h2>{audits.map(a => <div className="data-row" key={a.id}><div><strong>{a.action}</strong><div className="muted">{a.entityType} · {a.explanation ?? "No additional note"}</div></div><div className="muted">{a.modelVersion ?? "human"}<br/>{a.createdAt.toLocaleString()}</div></div>)}</section>
  </main>;
}
