import {redirect} from "next/navigation";
import {getCurrentEmployer} from "@/lib/session";
import {getAllCareerTracksAsync} from "@/lib/careerTracks.server";
import {createJob} from "@/actions/employer";
import Link from "next/link";
import {JobDraftActions,JobSaveStatus} from "@/components/JobDraftControls";
import EmployerHeader from "@/components/EmployerHeader";
import JobHiringAssistant from "@/components/JobHiringAssistant";
import {prisma} from "@/lib/db";
import DocumentUpload from "@/components/DocumentUpload";

function Section({title,number,icon,children}:{title:string;number:string;icon:string;children:React.ReactNode}){return <section className="pjob-section"><header><h2>{icon}　{title}</h2><small>SECTION {number}/04</small></header><div className="pjob-section-body">{children}</div></section>}
export default async function NewJob(){const ctx=await getCurrentEmployer();if(!ctx)redirect("/login");if(ctx.employer.verificationStatus!=="APPROVED")return <main className="pjob-pending"><h1>Create Job Opportunity</h1><p>Your employer account is pending administrator verification. Once approved, you&apos;ll be able to publish roles here.</p></main>;const [tracks,recentJobs]=await Promise.all([getAllCareerTracksAsync(),prisma.job.findMany({where:{employerId:ctx.employer.id},orderBy:{createdAt:"desc"},take:2})]);return <main className="pjob-page">
  <EmployerHeader company={ctx.employer.company} userName={ctx.user.name} active="post"/>
  <header className="pjob-top"><div><small><Link href="/employer/dashboard">OPPORTUNITIES</Link>　›　CREATE NEW OPPORTUNITY</small><h1>Create Job Opportunity</h1></div><Link className="pjob-discard" href="/employer/dashboard">Discard</Link><JobSaveStatus/></header>
  <form id="create-job-form" action={createJob}><div className="pjob-layout"><div className="pjob-main">
    <Section title="Basic Information" number="01" icon="ⓘ"><label className="wide">Job Title<input name="title" placeholder="e.g. Senior Software Engineer, Platform" required/><small>A clear, standard title helps the AI match candidates more accurately.</small></label><label>Department<select name="department"><option>Engineering</option><option>Product</option><option>Data & AI</option></select></label><label>Career Track<select name="careerTrack">{tracks.map(t=><option value={t.id} key={t.id}>{t.label}</option>)}</select></label><label>Employment Type<select name="employmentType"><option>Full-time</option><option>Part-time</option><option>Contract</option></select></label><label>Location<input name="location" placeholder="e.g. Riyadh, Saudi Arabia"/></label><fieldset className="wide"><legend>Work Arrangement</legend><div className="pjob-arrangement"><label><input type="radio" name="arrangement" value="on-site" defaultChecked/>⌂　 On-site</label><label><input type="radio" name="arrangement" value="hybrid"/>♙　 Hybrid</label><label><input type="radio" name="arrangement" value="remote"/>◎　 Remote</label></div></fieldset></Section>
    <Section title="Role Description" number="02" icon="☰"><div className="pjob-editor wide"><header>B　　<i>I</i>　　☷　　☷　　│　　↗</header><textarea name="description" placeholder="Describe responsibilities, expected outcomes, and what success looks like..."/><aside><b>✦　WRITING TIP</b><p>Use action-oriented language. Instead of “Responsible for reports,” try “Delivers weekly performance insights to key stakeholders to drive quarterly strategy.”</p></aside></div><div className="wide"><DocumentUpload label="Job description or requirements document"/></div></Section>
    <Section title="Candidate Requirements" number="03" icon="▣"><label>Required Skills<div className="pjob-token-input"><span>React.js　×</span><span>Node.js　×</span><span>PostgreSQL　×</span><input name="skills" placeholder="Add skill..." defaultValue="React.js:3, Node.js:3, PostgreSQL:3"/></div><small>WEIGHT: HIGH IMPORTANCE</small></label><label>Preferred Skills (Nice-to-have)<div className="pjob-token-input muted-tokens"><span>AWS　×</span><span>Docker　×</span><input name="preferredSkills" placeholder="Add skill..." defaultValue="AWS:1, Docker:1"/></div><small>WEIGHT: MEDIUM IMPORTANCE</small></label><label>Minimum Experience<select name="minExperience" defaultValue="36"><option value="0">Entry level</option><option value="36">3-5 Years</option><option value="60">5+ Years</option></select></label><label>Education Level<select><option>Bachelor&apos;s Degree</option><option>Master&apos;s Degree</option></select></label><label>Languages<div className="pjob-token-input muted-tokens"><span>English</span><span>French</span><input/></div></label><label className="wide certs">Required Certifications<input name="certifications" placeholder="＋　Add Certification"/></label></Section>
    <Section title="Hiring Preferences" number="04" icon="⚙"><div className="pjob-switch-grid wide"><label><input type="checkbox" name="blindReview" defaultChecked/><i/><span><b>Blind candidate review</b><small>Hide names, gender, and photos to reduce unconscious bias in the early stages.</small></span></label><label><input type="checkbox"/><i/><span><b>Portfolio required</b><small>Mandatory link or document upload for creative or technical evidence.</small></span></label><label><input type="checkbox" defaultChecked/><i/><span><b>Recent graduates accepted</b><small>Encourage applications from early-career talent and recent alumni.</small></span></label><label><input type="checkbox" defaultChecked/><i/><span><b>AI-assisted ranking</b><small>Use evidence-based AI scoring to rank the most qualified candidates automatically.</small></span></label></div></Section>
    <section className="pjob-oversight"><span>▣</span><div><b>Responsible AI Oversight</b><p>AI helps evaluate and organize candidate evidence. Final hiring decisions always remain under human oversight.</p></div><Link href="/policies/responsible-ai">Learn More</Link></section>
  </div><aside className="pjob-aside"><JobHiringAssistant/><section className="pjob-recent"><h3>RELATED RECENT POSTINGS</h3>{recentJobs.length?recentJobs.map(job=><Link href={`/employer/jobs/${job.id}`} key={job.id}><b>{job.title}</b><span>{job.careerTrack.replaceAll("-"," ")} • {job.createdAt.toLocaleDateString("en-SA",{month:"short",day:"numeric"})}</span><i>→</i></Link>):<p>No previous opportunities yet.</p>}</section></aside></div>
  <footer className="pjob-footer"><JobDraftActions/><span><small>ESTIMATED REACH</small><b>1,200+ Qualified Talent</b></span><button type="submit">Publish Opportunity　♧</button></footer></form>
  </main>}
