import { redirect } from "next/navigation";
import { prisma } from "@/lib/db";
import { getCurrentAdmin } from "@/lib/session";
import { captureMonitoringSnapshot } from "@/actions/governance";

export default async function MonitoringPage() {
  const ctx = await getCurrentAdmin(); if (!ctx) redirect("/login");
  const snapshots = await prisma.monitoringSnapshot.findMany({ orderBy: { createdAt: "desc" }, take: 12 });
  const latest = snapshots[0];
  return <main className="page-shell"><div className="data-row"><div><span className="eyebrow">Model assurance</span><h1 className="page-title">Fairness, drift and data sufficiency</h1></div><form action={captureMonitoringSnapshot}><button className="button primary">Capture current snapshot</button></form></div><p className="muted">Prototype thresholds: at least 20 outcomes; watch at ±5 score points or ±8 percentage points outcome drift; pause at ±10 or ±15.</p>{latest ? <><div className="grid-3" style={{ marginTop: 26 }}><div className="card"><span className="muted">Monitoring status</span><div className="metric" style={{ fontSize: 24 }}>{latest.status}</div></div><div className="card"><span className="muted">Eligible sample</span><div className="metric">{latest.sampleSize}</div><span className="muted">minimum 20</span></div><div className="card"><span className="muted">Model version</span><div className="metric" style={{ fontSize: 22 }}>{latest.modelVersion}</div></div></div>{latest.sampleSize < 20 && <div className="notice" style={{ marginTop: 18 }}><strong>Insufficient data:</strong> fairness and performance conclusions are suppressed. These records may be inspected, but must not justify a model or policy change.</div>}<section className="card" style={{ marginTop: 18 }}><h2>Monitoring history</h2>{snapshots.map(s => <div className="data-row" key={s.id}><div><strong>{s.status}</strong><div className="muted">Average score {s.averageScore.toFixed(1)} · Outcome rate {(s.outcomeRate * 100).toFixed(1)}%</div></div><div className="muted">Score drift {s.scoreDrift >= 0 ? "+" : ""}{s.scoreDrift.toFixed(1)}<br/>Outcome drift {(s.outcomeDrift * 100).toFixed(1)} pp</div></div>)}</section></> : <div className="notice" style={{ marginTop: 26 }}>Capture the first monitoring snapshot to establish a baseline.</div>}<section className="card" style={{ marginTop: 18 }}><h2>Fairness evaluation contract</h2><div className="grid-3"><div><strong>Permitted grouping</strong><p className="muted">Only approved, aggregate evaluation groups with a documented fairness purpose.</p></div><div><strong>Minimum group size</strong><p className="muted">No comparison or display for a group containing fewer than 20 outcomes.</p></div><div><strong>Response</strong><p className="muted">Material disparity pauses automated ranking and opens a human investigation.</p></div></div></section></main>;
}
